FROM python:3.11 AS base
RUN apt-get install build-dep python-psycopg2
WORKDIR /app
COPY . .
RUN pip install poetry==1.7.1
RUN poetry install
RUN poetry run prisma generate
RUN poetry run prisma generate --watch &
EXPOSE 8000
CMD poetry run python bot.py & poetry run uvicorn main:app --host 0.0.0.0 --port 8000 --reload