FROM python:3.11 AS base
WORKDIR /app
COPY . .
RUN pip install poetry==1.7.1
RUN poetry install
RUN poetry run prisma generate
RUN poetry run prisma migrate deploy
EXPOSE 8000

# should be on a separate dockerfile but we are saving disk space
CMD poetry run python bot.py & poetry run uvicorn main:app --host 0.0.0.0 --port 8000