FROM python:3.11 AS base
WORKDIR /app
COPY . .
RUN pip install poetry==1.7.1
RUN poetry install
RUN poetry run prisma generate
RUN poetry run prisma generate --watch &
EXPOSE 8000
# CMD poetry run uvicorn main:app --reload --host 0.0.0.0 --port 8000
CMD poetry run python bot.py