from prisma import Prisma

db = Prisma()
db.connect()
# res = db.user.create(
#     data={
#         "id": "test",
#         "telegramId": "test",
#         "telegramThread": {
#             "create": {
#                 "id": "test",
#                 "platform": "telegram",
#             }
#         },
#     }
# )

res2 = db.transaction.create_many(
    data=[
        {
            "amountOut": "1020",
            "amountIn": "0",
            "category": "Miscellaneous",
            "description": "test transaction",
            "sourceOrPayee": "wallmart",
            "transactionDate": "20231212",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "502",
            "amountIn": "0",
            "category": "Transportation",
            "description": "bus fare",
            "sourceOrPayee": "public transport",
            "transactionDate": "20230612",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "1202",
            "amountIn": "0",
            "category": "Entertainment",
            "description": "movie night",
            "sourceOrPayee": "cinema",
            "transactionDate": "20230505",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "2020",
            "amountIn": "0",
            "category": "RentAndMortgage",
            "description": "monthly rent",
            "sourceOrPayee": "landlord",
            "transactionDate": "20230510",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "3055",
            "amountIn": "0",
            "category": "FoodAndDining",
            "description": "takeout dinner",
            "sourceOrPayee": "local restaurant",
            "transactionDate": "20230515",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "50",
            "amountIn": "0",
            "category": "Grocery",
            "description": "weekly groceries",
            "sourceOrPayee": "local supermarket",
            "transactionDate": "20230705",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "120",
            "amountIn": "0",
            "category": "FoodAndDining",
            "description": "dinner with friends",
            "sourceOrPayee": "restaurant",
            "transactionDate": "20230712",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "1500",
            "amountIn": "0",
            "category": "RentAndMortgage",
            "description": "monthly rent",
            "sourceOrPayee": "landlord",
            "transactionDate": "20230715",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "80",
            "amountIn": "0",
            "category": "Utilities",
            "description": "electricity bill",
            "sourceOrPayee": "utility company",
            "transactionDate": "20230720",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "30",
            "amountIn": "0",
            "category": "Transportation",
            "description": "bus fare",
            "sourceOrPayee": "public transportation",
            "transactionDate": "20230725",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "90",
            "amountIn": "0",
            "category": "Healthcare",
            "description": "prescription medicine",
            "sourceOrPayee": "pharmacy",
            "transactionDate": "20230412",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "40",
            "amountIn": "0",
            "category": "Clothing",
            "description": "new shoes",
            "sourceOrPayee": "shoe store",
            "transactionDate": "20230405",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "200",
            "amountIn": "0",
            "category": "Education",
            "description": "textbooks",
            "sourceOrPayee": "bookstore",
            "transactionDate": "20230410",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "25",
            "amountIn": "0",
            "category": "Miscellaneous",
            "description": "movie night",
            "sourceOrPayee": "cinema",
            "transactionDate": "20230415",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "500",
            "amountIn": "0",
            "category": "Grocery",
            "description": "weekly groceries",
            "sourceOrPayee": "local grocery store",
            "transactionDate": "20230705",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "80",
            "amountIn": "0",
            "category": "FoodAndDining",
            "description": "dinner with friends",
            "sourceOrPayee": "restaurant",
            "transactionDate": "20230715",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "1200",
            "amountIn": "0",
            "category": "RentAndMortgage",
            "description": "monthly rent",
            "sourceOrPayee": "landlord",
            "transactionDate": "20230712",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "150",
            "amountIn": "0",
            "category": "Utilities",
            "description": "electricity bill",
            "sourceOrPayee": "utility company",
            "transactionDate": "20230710",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "50",
            "amountIn": "0",
            "category": "Transportation",
            "description": "bus fare",
            "sourceOrPayee": "public transportation",
            "transactionDate": "20230720",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "75",
            "amountIn": "0",
            "category": "Healthcare",
            "description": "prescription medication",
            "sourceOrPayee": "pharmacy",
            "transactionDate": "20230605",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "60",
            "amountIn": "0",
            "category": "Clothing",
            "description": "new pair of jeans",
            "sourceOrPayee": "clothing store",
            "transactionDate": "20230615",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "200",
            "amountIn": "0",
            "category": "Education",
            "description": "textbooks for the semester",
            "sourceOrPayee": "bookstore",
            "transactionDate": "20230625",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "40",
            "amountIn": "0",
            "category": "Entertainment",
            "description": "movie night",
            "sourceOrPayee": "movie theater",
            "transactionDate": "20230905",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "0",
            "amountIn": "1500",
            "category": "Miscellaneous",
            "description": "monthly income",
            "sourceOrPayee": "employer",
            "transactionDate": "20230912",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "0",
            "amountIn": "1500",
            "category": "Miscellaneous",
            "description": "monthly income",
            "sourceOrPayee": "employer",
            "transactionDate": "20230112",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "0",
            "amountIn": "1500",
            "category": "Miscellaneous",
            "description": "monthly income",
            "sourceOrPayee": "employer",
            "transactionDate": "20230212",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "0",
            "amountIn": "1500",
            "category": "Miscellaneous",
            "description": "monthly income",
            "sourceOrPayee": "employer",
            "transactionDate": "20230312",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "0",
            "amountIn": "1500",
            "category": "Miscellaneous",
            "description": "monthly income",
            "sourceOrPayee": "employer",
            "transactionDate": "20230412",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "0",
            "amountIn": "1500",
            "category": "Miscellaneous",
            "description": "monthly income",
            "sourceOrPayee": "employer",
            "transactionDate": "20230512",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "0",
            "amountIn": "1500",
            "category": "Miscellaneous",
            "description": "monthly income",
            "sourceOrPayee": "employer",
            "transactionDate": "20230612",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "0",
            "amountIn": "1500",
            "category": "Miscellaneous",
            "description": "monthly income",
            "sourceOrPayee": "employer",
            "transactionDate": "20230712",
            "currency": "USD",
            "userId": "test",
        },
        {
            "amountOut": "0",
            "amountIn": "1500",
            "category": "Miscellaneous",
            "description": "monthly income",
            "sourceOrPayee": "employer",
            "transactionDate": "20230812",
            "currency": "USD",
            "userId": "test",
        },
    ]
)
# print(res)
print(res2)
db.disconnect()
